### PR TITLE
Add Recommendations

### LINKED ISSUE #78: Recommendations
## User Story

As a User,
I want to be given a list of movie recommendations,
So that I can more easily discover new movies which I am likely to enjoy.

## Additional Context

A list of recommended movies will be provided to the user based off of the movies in their favourites list, if the list is empty, then it will simply display the most popular movies at the time.

## Acceptance Criteria

- [ ] A list of recommendations is provided to the user.
- [ ] Recommendations list is based off movies similar to movies found in favoutites list.
- [ ] Recommendations list defaults to showing the current most popular movies when favourites list is empty.

### PR DESCRIPTION
**Pull request by samcordner**
Adds 12 Recommendations underneath the users friends list based on the the content of their favorites list. This uses the existing movieDB database's recommendations feature. 

 - The recommendations are generated based on the top recommendations of the users first 12 favorites (if the user has <12, then multiple recommendations from each favorite are used).

1fav

- If the user has no favorites (or in rare cases the API can return no recommendations for a film), then the 12 most popular films are recommended.

nofavs

Ideally merge this after #82

Closes #78

### CODE REVIEW

**Comment by klam656** [comment]
Hey Sam, I try to run your code, it seems does not work on my machine. When I clicked on the favourite button. it shows me this.
Screenshot 2023-10-12 at 12 22 40 PM

Try login to my account: 
    username: 11 
    password: 11
and see whether if you get the same error. 

Further info about the error: 
Screenshot 2023-10-12 at 12 28 40 PM

**Comment by samcordner** [comment]
> Hey Sam, I try to run your code, it seems does not work on my machine. When I clicked on the favourite button. it shows me this. Screenshot 2023-10-12 at 12 22 40 PM
> 
> Try login to my account: username: 11 password: 11 and see whether if you get the same error.
> 
> Further info about the error: Screenshot 2023-10-12 at 12 28 40 PM

I think that your token issue may be due to the particular user(in this case 11)'s auth token being expired. If you run npm run installAll from the root folder, then logout and login, it should be fixed.

I have noticed some other issues with the fetching of favorites on this account compared to the other accounts I used for testing, which are likely a result of Sukhleen's Backend Changes as mentioned on Discord. 

I think It is probably wise to delay this PR's merge until Sukhleen's Backend Changes are merged, as they have the potential to break this functionality.

**Comment by samcordner** [comment]
The display is now fixed according to the changes from #84.

**Review by klam656 — APPROVED** [review]
The recommendation looks good, and code look clean and tidy, no need to refactorise! 
Good to merge. Good job Sam.

**Pull request merged**
