### PR TITLE
Implement Basic Version of Favourites Page

### PR DESCRIPTION
**Pull request by vdav02**
This PR adds

- a button in the navbar which redirects to the favourites page
- a favourites page, but without the implementation of displaying movies.

While this PR primarily serves to prevent #56 being blocked by not having a favourites page to work on, it still works towards closing #53 

Further implementation of the favourites list functionality will come in later PR's

### CODE REVIEW

**Comment by leas022** [comment]
@MRlolface249 here are screenshots like you requested. I'll try to get an automated GitHub action to run the project and take screenshots, but this will have to work for the meantime.

image
image

**Review by leas022 — CHANGES_REQUESTED** [review]
Almost everything is looking good thanks guys. The button and new page will be enough for @MRlolface249 and I to get started on our issue/new feature implementation. The only issue I picked up on is a vite/react warning logged to the console:

```
11:41:40 pm [vite] warning: The character ">" is not valid inside a JSX element
26 |              <Route path="/signup" element={!user ? <Signup /> : <Navigate to="/" />} />
27 |              <Route path="/favourites" element={user ? <Favourites /> : <Navigate to="/signup" />} />
28 |              />
   |               ^
29 |            </Routes>
30 |          </div>

```

I think the issue is just the double `/>` in `App.jsx` - hopefully removing the second closing tag will fix the issue. But apart from that I'm happy with the changes.

**Comment by vdav02** [comment]
> Almost everything is looking good thanks guys. The button and new page will be enough for @MRlolface249 and I to get started on our issue/new feature implementation. The only issue I picked up on is a vite/react warning logged to the console:
> 
> ```
> 11:41:40 pm [vite] warning: The character ">" is not valid inside a JSX element
> 26 |              <Route path="/signup" element={!user ? <Signup /> : <Navigate to="/" />} />
> 27 |              <Route path="/favourites" element={user ? <Favourites /> : <Navigate to="/signup" />} />
> 28 |              />
>    |               ^
> 29 |            </Routes>
> 30 |          </div>
> ```
> 
> I think the issue is just the double `/>` in `App.jsx` on line 42 - hopefully removing the second closing tag will fix the issue. But apart from that I'm happy with the changes.

Thanks for catching that typo Luca, looks like in my rush to get this up I just checked to make sure it compiled and ran properly. Just made sure it ran and tested the button functionality to make sure it worked as expected. Thanks for catching that, I've made a commit now which should fix the typo.

**Review by leas022 — APPROVED** [review]
Thanks for fixing the issue. Everything is looking good now - happy for changes to be merged.

**Pull request merged**
