### PR TITLE
Add comments

### PR DESCRIPTION
**Pull request by klam656**
Since the last team have not documented their code very well, which make us have very hard time to read and understand their code. I decided to add more meaningful comment, mostly in Js. I hope this will help us interpret the code and the whole software product more.

### CODE REVIEW

**Review by vdav02 — CHANGES_REQUESTED** [review]
These comments look really good Kenny, thank you for writing them out! They'll go a long way in making it easier to understand the code - just reading it now I was able to go through the files much quicker with the help of the comments. Just one thing I wanted to confirm - this PR isn't saying that these are all the comments to be added to the project right? As I can think of a couple more files where comments would definitely be a valuable addition.

**Comment by klam656** [comment]
Hi Vishva, Thank you for your kind words! I'm glad to hear that the comments have been helpful in understanding the code. To address your question, yes, the comments in this PR are all that I had planned to add initially. However, I appreciate you pointing out that there could be other files that might benefit from additional comments.mI think other files are mostly related to fronted (React), so that it is really difficult to me to comment about it. I'm open to suggestions and would be happy to consider adding more comments where needed. Please feel free to share your thoughts on specific areas or files that you think could use further clarification.

**Comment by vdav02** [comment]
Awesome, thanks for your response. I understand that your expertise may not be front-end, and that's totally okay. Thank you for clarifying - I'm thinking of some of the files such as the components like MovieCard. I'll talk to the relevant people focused on front-end in our group on the Discord server to see if they would be able to take a look. Happy to merge it now - thanks for your hard work!!

**Review by vdav02 — APPROVED** [review]
Code looks good to me now, happy to merge

**Pull request merged**
