### PR TITLE
Implement back-end support for favorite movies list feature

### PR DESCRIPTION
**Pull request by skau811**
This Pull Request introduces few additions to the backend to support the functionality of adding, viewing, and editing favorite movies for users:

Server-Side Endpoints
   - New endpoints have been added to handle requests related to the favorite movies list.

User Schema Updates
   - The User schema has been extended with a new favorites array. This array holds the IDs of movies that users mark as favorites, enabling persistent storage of user preferences.

Instance Methods in userModel
   - Relevant instance methods have been integrated into userModel to facilitate database write operations.

With these additions, the backend now has the relevant functions to incorporate the favorite movies list feature, thereby progressing towards the closure of #53 .

### CODE REVIEW

**Comment by MRlolface249** [comment]
Would you be able to provide some screenshots or documentation for the testing please?

**Comment by skau811** [comment]
The testing of the endpoints was done using POSTMAN. Below are the requested screenshots which show the relvant requests and the state of the user document as a result of those interactions:

Background : The screenshots below are the result of the interactions with the user document with lightYG as the username, all the requests to the endpoints include the authorization token in the header (generated during login/signup), and take place using this token.

For further context: 
image



**Testing the get all favorite movies endpoint**
image
From mongoDB database:
image

**Testing the add to favorites endpoint**
image

image
From mongoDB (889 is now present in the list):
image

**Testing the remove from favorites endpoint**
image
From mongoDB (1235 is not present there):
image

**Testing if a particular movie is present in favorites list endpoint**
image
Since 1235 was removed in the previous remove request, we get this message.

**Comment by MRlolface249** [comment]
thankyou for adding the documentation

**Review by vdav02 — APPROVED** [review]
Hi Sukhleen, thank you for this contribution. The code looked good to me, and adding the screenshots of the testing you conducted with Postman confirmed this as well. This pull request is critical for the functionality of the Favourites list, thanks for your hard work! It looks good to me and I'm happy to merge it in now!

**Pull request merged**
