### PR TITLE
Favourites styling

### PR DESCRIPTION
**Pull request by MRlolface249**
some styling for the favourites page which will become dynamically generated once some hooks are implemented.

### CODE REVIEW

**Review by vdav02 — CHANGES_REQUESTED** [review]
Hey Alex, the changes look all good to me. The styling changes really improve the feel of our website, and go a long way in the effect it'll have on our users. As per the convention we established earlier, since this is a frontend oriented pull request if you could just attach some screenshots of the website that'd be awesome! Also, there's a couple of conflicts that have popped up as well, if you'd be happy to take a look at those as well that'd be awesome. If you need any help reviewing the conflicts let me know as well, I'd be happy to help! Apart from that, it all looks good to me - nice work :))

**Comment by leas022** [comment]
image

**Comment by MRlolface249** [comment]
I have resolved the merge conflicts, if you want to just double check that I haven't deleted anything important. luca has provided the screenshots requested

**Comment by leas022** [comment]
> I have resolved the merge conflicts, if you want to just double check that I haven't deleted anything important. luca has provided the screenshots requested

Thank you for the photo credit

**Comment by leas022** [comment]
I am getting this issue when I run the branch - just wanted to determine where this bug is coming from

```
JsonWebTokenError: jwt malformed
    at module.exports [as verify] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\jsonwebtoken\verify.js:70:17)
    at requireAuth (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\src\middleware\requireAuth.js:14:27)
    at Layer.handle [as handle_request] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:421:3)
JsonWebTokenError: jwt malformed
    at module.exports [as verify] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\jsonwebtoken\verify.js:70:17)
    at requireAuth (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\src\middleware\requireAuth.js:14:27)
    at Layer.handle [as handle_request] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\Users\lucae\OneDrive - The University of Auckland\Desktop\UOA\2023\SOFTENG310\a2-alex\W.A.K\server\node_modules\express\lib\router\index.js:421:3)
```

**Comment by leas022** [comment]
Okay I have checked out the commit before the merge conflict commit - the error message is not displaying when I run the project from this commit. Either the bug was already in main (and is only being exposed now) or the bug was caused when the merge conflict was resolved.

**Comment by leas022** [comment]
Is someone else able to run the project from this fork and confirm they are getting the same error logged to the console?

**Comment by MRlolface249** [comment]
I have run it as well, and get the same error

**Review by leas022 — APPROVED** [review]
Okay it appears the issue is actually slightly larger than first expected. It turns out you can log in as a made up user - there is no credential validation so a error message is not being shown to users logging in as a user who does not exist. This causes the malformed JWT when accessing the authContext. I think we need to create a seperate issue as this bug is already in main. Since the PR is not the cause of the bug I am happy to approve and merge to main.

**Review by vdav02 — APPROVED** [review]
This code looks good to me. After extensive testing, it appears the bug which we're getting is due to users being able to 'sign in' to the website with any given email and password without first creating an account with that email and password through the sign up feature. In that case, the error (documented earlier in the conversation) is encountered. This isn't an issue with this particular PR, but rather an issue in main. To deal with this, we'll have to create a separate issue and work on a fix for this bug (@leas022 is creating the issue now). Therefore, I'm happy to merge this particular PR into main. Nice work Alex!

**Pull request merged**
